server:
  port: 90

eureka:
  client:
    service-url:
      defaultZone: http://localhost:52700/eureka/

logging:
  level:
    root: info
    org:
      springframework:
        security: debug

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 1

rmms:
  jdbc:
    unique-resource-name: rmmsDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@192.168.200.70:1521:testdb
    username: rmms_user
    password: rmmsusertest
    maxPoolSize: 8
    minPoolSize: 8