server:
  port: 52752

eureka:
  client:
    service-url:
      defaultZone: http://localhost:52700/eureka/

logging:
  level:
    root: info

ems:
  jdbc:
    unique-resource-name: emsDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://192.168.200.62;DatabaseName=DB_EMS_20200323
    username: sa
    password: 111.aaa
    maxPoolSize: 8
    minPoolSize: 8