server:
  port: 52751

eureka:
  client:
    service-url:
      defaultZone: http://localhost:52700/eureka/

logging:
  level:
    root: info

rmms:
  jdbc:
    unique-resource-name: rmmsDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    jdbc-url: jdbc:oracle:thin:@192.168.200.70:1521:testdb
    username: rmms_user
    password: rmmsusertest
    maxPoolSize: 8
    minPoolSize: 8