server:
  port: 52752

eureka:
  client:
    service-url:
      defaultZone: http://localhost:52700/eureka/

logging:
  config: classpath:log4j2-prod.xml
  level:
    root: info

weight:
  jdbc:
    unique-resource-name: weightDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://192.168.57.152:1433;DatabaseName=WY_DATAMANAGE
    username: xauser
    password: xauser
    maxPoolSize: 8
    minPoolSize: 8

spring:
  cloud:
    stream:
      default-binder: kafka  #与consul 使用时需要指定 binder
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        carriage-insert-channel: # 输出通道
          destination: carriage-insert  # 对应的topic
          content-type: application/json
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      retries: 3
      buffer-memory: 40960
      batch-size: 4096
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.fangda.erp.weight.kafka.message